import { CompetencyType, DetailedUserModel, ExpertUserModel, TeamStatusses, UserCompetencyType, UsersListItemModel, UserTypes } from 'src/features/statistics/models'

export const fakeAnyUsers: UsersListItemModel[] = [
  {
    id: 1,
    lastName: 'Иванов',
    firstName: 'Илья',
    middleName: 'Сергеевич',
    academicGroup: 'ФО-320001',
    login: 'ivAnov',
    about: '',
    userType: UserTypes.Student,
    phoneNumber: '+79090207012',
    email: '14neruin@gmail.com',
  },
  {
    id: 2,
    lastName: 'Алексеев',
    firstName: 'Иван',
    middleName: 'Иванович',
    academicGroup: 'ФО-320002',
    login: 'user123',
    about: '',
    userType: UserTypes.Student,
    phoneNumber: '+790901237012',
    email: '1аe2uin@gmail.com',
  },
  {
    id: 3,
    lastName: 'Admin',
    firstName: 'Admin',
    middleName: '',
    academicGroup: '',
    login: 'admin',
    about: '',
    userType: UserTypes.Admin,
    phoneNumber: '',
    email: 'admin@gmail.com',
  },
  {
    id: 4,
    lastName: 'Fake',
    firstName: 'Admin',
    middleName: '',
    academicGroup: '',
    login: 'test-admin',
    about: '',
    userType: UserTypes.Admin,
    phoneNumber: '',
    email: 'test-admin@gmail.com',
  },
  {
    id: 5,
    lastName: 'Test',
    firstName: 'Expert',
    middleName: '',
    academicGroup: '',
    login: 'test-expert',
    about: '',
    userType: UserTypes.Expert,
    phoneNumber: '',
    email: 'test-expert@gmail.com',
  },
  {
    id: 6,
    lastName: 'Максимов',
    firstName: 'Андрей',
    middleName: 'Андреевич',
    academicGroup: 'ФО-320002',
    login: 'user123',
    about: '',
    userType: UserTypes.Student,
    phoneNumber: '+790901237012',
    email: '1аe2uin@gmail.com',
  },
  {
    id: 7,
    lastName: 'Андреев',
    firstName: 'Андрей',
    middleName: 'Олегович',
    academicGroup: '',
    login: 'expert',
    about: '',
    userType: UserTypes.Expert,
    phoneNumber: '',
    email: 'expert@gmail.com',
  },
]

export const fakeExperts: ExpertUserModel[] = [
  {
    id: 5,
    lastName: 'Test',
    firstName: 'Expert',
    middleName: '',
    auditoriumId: 1,
  },
  {
    id: 7,
    lastName: 'Андреев',
    firstName: 'Андрей',
    middleName: 'Олегович',
  },
  {
    id: 8,
    lastName: 'Иванов',
    firstName: 'Максим',
    middleName: 'Андреевич',
    auditoriumId: 2,
  },
]

export const fakeDetailedUser: DetailedUserModel = {
  id: 6,
  eventId: 1,
  lastName: 'Максимов',
  firstName: 'Андрей',
  middleName: 'Андреевич',
  academicGroup: 'ФО-320002',
  login: 'user123',
  about: 'Работаю на React и Angular',
  userType: UserTypes.Student,
  phoneNumber: '+790901237012',
  email: '1аe2uin@gmail.com',
  project: {
    id: 0,
    name: 'Разработка самого лучшего проекта',
    curator: 'Хлебников Н.А.',
    organization: 'УрФУ',
    contacts: 'Иванов Иван Иванович - 89990990909',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus ratione error vitae consectetur repellat recusandae enim veniam ex numquam, laudantium dicta quisquam quaerat alias perferendis consequatur tempore incidunt ipsam officiis?',
    purpose: 'Создание приложения для расчета разности массы в момент когда вы находитесь на планете земля и на других планетах нашей солнечной системы',
    result: 'Прототип приложения',
  },
  role: {
    id: 0,
    name: 'Frontend',
  },
  team: {
    id: 1,
    name: 'Coders',
    teamStatus: TeamStatusses.Incomplete,
    users: [],
  },
  competencies: [
    {
      id: 0,
      name: 'Frontend',
      competencyType: CompetencyType.HardSkill,
      userCompetencyType: UserCompetencyType.Current,
    },
    {
      id: 1,
      name: 'UI/UX',
      competencyType: CompetencyType.HardSkill,
      userCompetencyType: UserCompetencyType.Current,
    },
    {
      id: 2,
      name: 'Аналитика',
      competencyType: CompetencyType.SoftSkill,
      userCompetencyType: UserCompetencyType.Current,
    },
    {
      id: 3,
      name: 'Проектирование интерфейсов',
      competencyType: CompetencyType.HardSkill,
      userCompetencyType: UserCompetencyType.Desirable,
    },
  ],
  registrationDate: new Date().toString(),
}
