import {
  UserTypes,
  UserModel,
  CompetencyType,
  UserCompetencyType,
} from 'src/features/statistics/models'

export const fakeFreeStudents: UserModel[] = [
  {
    id: 0,
    lastName: 'Иванов',
    firstName: 'Илья',
    middleName: 'Сергеевич',
    academicGroup: 'ФО-320001',
    login: '',
    about: '',
    userType: UserTypes.Student,
    phoneNumber: '+79090207012',
    email: '14neruin@gmail.com',
    competencies: [
      {
        id: 0,
        name: 'Frontend',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Current,
      },
      {
        id: 1,
        name: 'UI/UX',
        competencyType: CompetencyType.SoftSkill,
        userCompetencyType: UserCompetencyType.Current,
      },
      {
        id: 2,
        name: 'Аналитика',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Desirable,
      },
      {
        id: 3,
        name: 'Менеджемент',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Desirable,
      },
      {
        id: 4,
        name: 'Управление проектами',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Desirable,
      },
      {
        id: 5,
        name: 'Системный анализ',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Desirable,
      },
    ],
  },
  {
    id: 1,
    lastName: 'Иванов',
    firstName: 'Илья',
    middleName: 'Сергеевич',
    academicGroup: 'ФО-320001',
    login: '',
    about: '',
    userType: UserTypes.Student,
    phoneNumber: '+79090207012',
    email: '14neruin@gmail.com',
    competencies: [
      {
        id: 0,
        name: 'Frontend',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Current,
      },
      {
        id: 1,
        name: 'UI/UX',
        competencyType: CompetencyType.SoftSkill,
        userCompetencyType: UserCompetencyType.Current,
      },
      {
        id: 2,
        name: 'Аналитика',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Desirable,
      },
    ],
  },
  {
    id: 3,
    lastName: 'Иванов',
    firstName: 'Илья',
    middleName: 'Сергеевич',
    academicGroup: 'ФО-320001',
    login: '',
    about: '',
    userType: UserTypes.Student,
    phoneNumber: '+79090207012',
    email: '14neruin@gmail.com',
    competencies: [
      {
        id: 0,
        name: 'Frontend',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Current,
      },
      {
        id: 1,
        name: 'UI/UX',
        competencyType: CompetencyType.SoftSkill,
        userCompetencyType: UserCompetencyType.Current,
      },
      {
        id: 2,
        name: 'Аналитика',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Desirable,
      },
    ],
  },
  {
    id: 4,
    lastName: 'Иванов',
    firstName: 'Илья',
    middleName: 'Сергеевич',
    academicGroup: 'ФО-320001',
    login: '',
    about: '',
    userType: UserTypes.Student,
    phoneNumber: '+79090207012',
    email: '14neruin@gmail.com',
    competencies: [
      {
        id: 0,
        name: 'Frontend',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Current,
      },
      {
        id: 1,
        name: 'UI/UX',
        competencyType: CompetencyType.SoftSkill,
        userCompetencyType: UserCompetencyType.Current,
      },
      {
        id: 2,
        name: 'Аналитика',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Desirable,
      },
    ],
  },
  {
    id: 5,
    lastName: 'Иванов',
    firstName: 'Илья',
    middleName: 'Сергеевич',
    academicGroup: 'ФО-320001',
    login: '',
    about: '',
    userType: UserTypes.Student,
    phoneNumber: '+79090207012',
    email: '14neruin@gmail.com',
    competencies: [
      {
        id: 0,
        name: 'Frontend',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Current,
      },
      {
        id: 1,
        name: 'UI/UX',
        competencyType: CompetencyType.SoftSkill,
        userCompetencyType: UserCompetencyType.Current,
      },
      {
        id: 2,
        name: 'Аналитика',
        competencyType: CompetencyType.HardSkill,
        userCompetencyType: UserCompetencyType.Desirable,
      },
    ],
  },
]
